***Health System Resilience in FCAS\***

Creating Merged and Cleaned Dataset

Step 1 Importing Libraries and Preparation

In [ ]:
import pandas as pd
import numpy as np
import itertools
from google.colab import files

Step 2 importing Files

In [ ]:
uploaded = files.upload()

Saving Countries.xlsx to Countries.xlsx
Saving GDP and health expenditure for  FCSL_data.csv to GDP and health expenditure for  FCSL_data.csv
Saving GNI for FCSL_data.csv to GNI for FCSL_data.csv
Saving life_expectancy_all_countries.csv to life_expectancy_all_countries.csv
Saving MD per 10000.csv to MD per 10000.csv
Saving Nursing and midwifery per 10000.csv to Nursing and midwifery per 10000.csv

2-1 Reading the Files

In [ ]:
countries_raw = pd.read_excel("Countries.xlsx")
md_raw = pd.read_csv("MD per 10000.csv")
nurse_raw = pd.read_csv("Nursing and midwifery per 10000.csv")
life_raw = pd.read_csv("life_expectancy_all_countries.csv")
gdphexp_raw = pd.read_csv("GDP and health expenditure for  FCSL_data.csv")
gni_raw = pd.read_csv("GNI for FCSL_data.csv")

Step 3 Creating Countries List

In [ ]:
countries = [countries_raw.columns[0]] + countries_raw.iloc[:, 0].dropna().tolist()
countries

['Afghanistan',
 'Burkina Faso',
 'Burundi',
 'Cameroon',
 'Central African Republic',
 'Chad',
 'Comoros',
 'Congo, Democratic Republic of',
 'Congo, Republic of',
 'Eritrea',
 'Ethiopia',
 'Guinea-Bissau',
 'Haiti',
 'Iraq',
 'Kiribati',
 'Lebanon',
 'Libya',
 'Mali',
 'Marshall Islands',
 'Micronesia, Federated States of',
 'Mozambique',
 'Myanmar',
 'Niger',
 'Nigeria',
 'Papua New Guinea',
 'São Tomé and Príncipe',
 'Solomon Islands',
 'Somalia',
 'South Sudan',
 'Sudan',
 'Syrian Arab Republic',
 'Timor-Leste',
 'Tuvalu',
 'Ukraine',
 'Venezuela, RB',
 'West Bank and Gaza (territory)',
 'Yemen, Republic of',
 'Zimbabwe']

3-1 Check Countries list

In [ ]:
len(countries)

38

In [ ]:
countries

['Afghanistan',
 'Burkina Faso',
 'Burundi',
 'Cameroon',
 'Central African Republic',
 'Chad',
 'Comoros',
 'Congo, Democratic Republic of',
 'Congo, Republic of',
 'Eritrea',
 'Ethiopia',
 'Guinea-Bissau',
 'Haiti',
 'Iraq',
 'Kiribati',
 'Lebanon',
 'Libya',
 'Mali',
 'Marshall Islands',
 'Micronesia, Federated States of',
 'Mozambique',
 'Myanmar',
 'Niger',
 'Nigeria',
 'Papua New Guinea',
 'São Tomé and Príncipe',
 'Solomon Islands',
 'Somalia',
 'South Sudan',
 'Sudan',
 'Syrian Arab Republic',
 'Timor-Leste',
 'Tuvalu',
 'Ukraine',
 'Venezuela, RB',
 'West Bank and Gaza (territory)',
 'Yemen, Republic of',
 'Zimbabwe']

3-2 Uniformity of country names

In [ ]:
country_map = {
    "Congo, Dem. Rep.": "Congo, Democratic Republic of",
    "Democratic Republic of the Congo": "Congo, Democratic Republic of",
    "Congo, Rep.": "Congo, Republic of",
    "Republic of Congo": "Congo, Republic of",
    "Congo": "Congo, Republic of",
    "Venezuela": "Venezuela, RB",
    "Venezuela (Bolivarian Republic of)": "Venezuela, RB",
    "Yemen, Rep.": "Yemen, Republic of",
    "Yemen": "Yemen, Republic of",
    "West Bank and Gaza": "West Bank and Gaza (territory)",
    "Syrian Arab Rep.": "Syrian Arab Republic",
    "Timor Leste": "Timor-Leste",
    "Sao Tome and Principe": "São Tomé and Príncipe",
    "Micronesia, Fed. Sts.": "Micronesia, Federated States of",
    "Micronesia (Federated States of)": "Micronesia, Federated States of"
}

def clean_country(x):
    x = str(x).strip()
    return country_map.get(x, x)

Step 4 Preparing (Cleaning) "MD" file

In [ ]:
md = md_raw[["Location", "Period", "FactValueNumeric"]].copy()
md = md.rename(columns={
    "Location": "country",
    "Period": "year",
    "FactValueNumeric": "physicians_per_10000"
})

md["country"] = md["country"].apply(clean_country)
md["year"] = pd.to_numeric(md["year"], errors="coerce")
md["physicians_per_10000"] = pd.to_numeric(md["physicians_per_10000"], errors="coerce")

md = md[md["country"].isin(countries)].copy()

md["physicians_per_1000"] = md["physicians_per_10000"] / 10

md = md[["country", "year", "physicians_per_1000"]].copy()
md.head()

            country  year  physicians_per_1000
0  Papua New Guinea  2024                0.046
2           Somalia  2024                0.065
3              Chad  2024                0.080
4           Burundi  2024                0.083
6          Cameroon  2024                0.088

4-1 Check "MD" file Counties

In [ ]:
sorted(md["country"].unique())

['Afghanistan',
 'Burkina Faso',
 'Burundi',
 'Cameroon',
 'Central African Republic',
 'Chad',
 'Comoros',
 'Congo, Democratic Republic of',
 'Congo, Republic of',
 'Eritrea',
 'Ethiopia',
 'Guinea-Bissau',
 'Haiti',
 'Iraq',
 'Kiribati',
 'Lebanon',
 'Libya',
 'Mali',
 'Marshall Islands',
 'Micronesia, Federated States of',
 'Mozambique',
 'Myanmar',
 'Niger',
 'Nigeria',
 'Papua New Guinea',
 'Solomon Islands',
 'Somalia',
 'South Sudan',
 'Sudan',
 'Syrian Arab Republic',
 'São Tomé and Príncipe',
 'Timor-Leste',
 'Tuvalu',
 'Ukraine',
 'Venezuela, RB',
 'Yemen, Republic of',
 'Zimbabwe']

In [ ]:
len(md["country"].unique())

37

Step 5 Preparing (Cleaning) "Nursing" File

In [ ]:
nurse = nurse_raw[["Location", "Period", "FactValueNumeric"]].copy()

nurse = nurse.rename(columns={
    "Location": "country",
    "Period": "year",
    "FactValueNumeric": "nurses_midwives_per_10000"
})

nurse["country"] = nurse["country"].apply(clean_country)
nurse["year"] = pd.to_numeric(nurse["year"], errors="coerce")
nurse["nurses_midwives_per_10000"] = pd.to_numeric(nurse["nurses_midwives_per_10000"], errors="coerce")

nurse = nurse[nurse["country"].isin(countries)].copy()

nurse["nurses_midwives_per_1000"] = nurse["nurses_midwives_per_10000"] / 10

nurse = nurse[["country", "year", "nurses_midwives_per_1000"]].copy()

nurse.head()

               country  year  nurses_midwives_per_1000
1             Ethiopia  2024                     1.085
3              Nigeria  2024                     1.152
8   Congo, Republic of  2024                     1.335
12            Zimbabwe  2024                     1.465
23     Solomon Islands  2024                     2.130

5-1 Check "Nursing" file Counties

In [ ]:
sorted(nurse["country"].unique())

['Afghanistan',
 'Burkina Faso',
 'Burundi',
 'Cameroon',
 'Central African Republic',
 'Chad',
 'Comoros',
 'Congo, Democratic Republic of',
 'Congo, Republic of',
 'Eritrea',
 'Ethiopia',
 'Guinea-Bissau',
 'Haiti',
 'Iraq',
 'Kiribati',
 'Lebanon',
 'Libya',
 'Mali',
 'Marshall Islands',
 'Micronesia, Federated States of',
 'Mozambique',
 'Myanmar',
 'Niger',
 'Nigeria',
 'Papua New Guinea',
 'Solomon Islands',
 'Somalia',
 'South Sudan',
 'Sudan',
 'Syrian Arab Republic',
 'São Tomé and Príncipe',
 'Timor-Leste',
 'Tuvalu',
 'Ukraine',
 'Venezuela, RB',
 'Yemen, Republic of',
 'Zimbabwe']

In [ ]:
len(nurse["country"].unique())

37

Step 6 Preparing (Cleaning) "life expectancy" File

In [ ]:
life_raw.head()

,economy,Country,YR2000,YR2001,YR2002,YR2003,YR2004,YR2005,YR2006,YR2007,...,YR2011,YR2012,YR2013,YR2014,YR2015,YR2016,YR2017,YR2018,YR2019,YR2020
0,POL,Poland,73.748780,74.200000,74.497561,74.597561,74.846341,74.995122,75.143902,75.243902,...,76.695122,76.746341,77.000000,77.602439,77.451220,77.851220,77.753659,77.602439,77.904878,76.400000
1,KEN,Kenya,56.084000,56.501000,56.759000,57.369000,57.947000,58.510000,59.059000,59.407000,...,61.283000,61.537000,61.729000,61.990000,62.279000,62.526000,62.725000,62.825000,62.939000,61.596000
2,CRI,Costa Rica,77.317000,77.609000,77.939000,78.214000,78.512000,78.877000,79.049000,79.098000,...,79.624000,79.925000,80.189000,80.231000,80.407000,79.988000,79.994000,80.090000,80.296000,79.725000
3,ARM,Armenia,72.880488,72.975610,72.826829,72.826829,73.026829,73.075610,72.824390,72.873171,...,73.817073,74.119512,74.621951,74.873171,74.870732,74.868293,75.217073,75.619512,76.221951,73.375610
4,VIR,Virgin Islands (U.S.),76.619512,77.621951,77.521951,77.521951,77.773171,77.421951,78.324390,76.863415,...,78.317073,78.517073,78.717073,78.868293,79.017073,79.168293,79.368293,79.519512,79.668293,79.819512

In [ ]:
life_raw.columns

Index(['economy', 'Country', 'YR2000', 'YR2001', 'YR2002', 'YR2003', 'YR2004',
       'YR2005', 'YR2006', 'YR2007', 'YR2008', 'YR2009', 'YR2010', 'YR2011',
       'YR2012', 'YR2013', 'YR2014', 'YR2015', 'YR2016', 'YR2017', 'YR2018',
       'YR2019', 'YR2020'],
      dtype='object')

In [ ]:
Index(['economy', 'Country', 'YR2000', 'YR2001', 'YR2002', 'YR2003', 'YR2004',
       'YR2005', 'YR2006', 'YR2007', 'YR2008', 'YR2009', 'YR2010', 'YR2011',
       'YR2012', 'YR2013', 'YR2014', 'YR2015', 'YR2016', 'YR2017', 'YR2018',
       'YR2019', 'YR2020'],
      dtype='object')

In [ ]:
life = life_raw.copy()

life["Country"] = life["Country"].apply(clean_country)

life = life[life["Country"].isin(countries)].copy()

year_cols = [c for c in life.columns if str(c).startswith("YR")]

life = life.melt(
    id_vars=["Country"],
    value_vars=year_cols,
    var_name="year",
    value_name="life_expectancy"
)

life = life.rename(columns={"Country": "country"})

life["year"] = life["year"].str.replace("YR", "", regex=False)
life["year"] = pd.to_numeric(life["year"], errors="coerce")

life["life_expectancy"] = pd.to_numeric(life["life_expectancy"], errors="coerce")

life = life[["country", "year", "life_expectancy"]].copy()

life.head()

                         country  year  life_expectancy
0             Congo, Republic of  2000           55.371
1  Congo, Democratic Republic of  2000           51.887
2                       Ethiopia  2000           50.880
3                          Niger  2000           49.172
4                       Kiribati  2000           64.674

In [ ]:
len(life["country"].unique())

37

In [ ]:
sorted(life["country"].unique())

['Afghanistan',
 'Burkina Faso',
 'Burundi',
 'Cameroon',
 'Central African Republic',
 'Chad',
 'Comoros',
 'Congo, Democratic Republic of',
 'Congo, Republic of',
 'Eritrea',
 'Ethiopia',
 'Guinea-Bissau',
 'Haiti',
 'Iraq',
 'Kiribati',
 'Lebanon',
 'Libya',
 'Mali',
 'Marshall Islands',
 'Micronesia, Federated States of',
 'Mozambique',
 'Myanmar',
 'Niger',
 'Nigeria',
 'Papua New Guinea',
 'Solomon Islands',
 'South Sudan',
 'Sudan',
 'Syrian Arab Republic',
 'São Tomé and Príncipe',
 'Timor-Leste',
 'Tuvalu',
 'Ukraine',
 'Venezuela, RB',
 'West Bank and Gaza (territory)',
 'Yemen, Republic of',
 'Zimbabwe']

Step 7 Preparing (Cleaning) "GNI" File

In [ ]:
gni_raw.head()

,Country Name,Country Code,Series Name,Series Code,2000 [YR2000],2001 [YR2001],2002 [YR2002],2003 [YR2003],2004 [YR2004],2005 [YR2005],...,2016 [YR2016],2017 [YR2017],2018 [YR2018],2019 [YR2019],2020 [YR2020],2021 [YR2021],2022 [YR2022],2023 [YR2023],2024 [YR2024],2025 [YR2025]
0,Afghanistan,AFG,"GNI per capita, PPP (current international $)",NY.GNP.PCAP.PP.CD,790,750,940,980,980,1090,...,2240,2360,2460,2620,2580,2160,2130,2210,..,..
1,Burkina Faso,BFA,"GNI per capita, PPP (current international $)",NY.GNP.PCAP.PP.CD,900,940,960,1030,1070,1160,...,1800,1970,2010,2140,2280,2340,2470,2610,2720,..
2,Cameroon,CMR,"GNI per capita, PPP (current international $)",NY.GNP.PCAP.PP.CD,1990,2050,2140,2290,2480,2530,...,3570,3700,3940,4150,4280,4720,5060,5300,5490,..
3,Central African Republic,CAF,"GNI per capita, PPP (current international $)",NY.GNP.PCAP.PP.CD,630,660,680,650,680,700,...,840,930,970,1060,1130,1210,1280,1330,1340,..
4,"Congo, Dem. Rep.",COD,"GNI per capita, PPP (current international $)",NY.GNP.PCAP.PP.CD,410,380,400,420,440,460,...,930,960,1010,990,1060,1360,1510,1680,1760,..

In [ ]:
gni_raw.columns

Index(['Country Name', 'Country Code', 'Series Name', 'Series Code',
       '2000 [YR2000]', '2001 [YR2001]', '2002 [YR2002]', '2003 [YR2003]',
       '2004 [YR2004]', '2005 [YR2005]', '2006 [YR2006]', '2007 [YR2007]',
       '2008 [YR2008]', '2009 [YR2009]', '2010 [YR2010]', '2011 [YR2011]',
       '2012 [YR2012]', '2013 [YR2013]', '2014 [YR2014]', '2015 [YR2015]',
       '2016 [YR2016]', '2017 [YR2017]', '2018 [YR2018]', '2019 [YR2019]',
       '2020 [YR2020]', '2021 [YR2021]', '2022 [YR2022]', '2023 [YR2023]',
       '2024 [YR2024]', '2025 [YR2025]'],
      dtype='object')

In [ ]:
gni = gni_raw.copy()

gni["Country Name"] = gni["Country Name"].apply(clean_country)

gni = gni[gni["Country Name"].isin(countries)].copy()

year_cols = [c for c in gni.columns if "[YR" in str(c)]

gni = gni.melt(
    id_vars=["Country Name"],
    value_vars=year_cols,
    var_name="year",
    value_name="gni_ppp_current_international"
)

gni = gni.rename(columns={"Country Name": "country"})

gni["year"] = gni["year"].str.extract(r"(\d{4})")
gni["year"] = pd.to_numeric(gni["year"], errors="coerce")

gni["gni_ppp_current_international"] = pd.to_numeric(
    gni["gni_ppp_current_international"].replace("..", pd.NA),
    errors="coerce"
)

gni = gni[["country", "year", "gni_ppp_current_international"]].copy()

gni.head()

                         country  year  gni_ppp_current_international
0                    Afghanistan  2000                          790.0
1                   Burkina Faso  2000                          900.0
2                       Cameroon  2000                         1990.0
3       Central African Republic  2000                          630.0
4  Congo, Democratic Republic of  2000                          410.0

In [ ]:
len(gni["country"].unique())

37

In [ ]:
sorted(gni["country"].unique())

['Afghanistan',
 'Burkina Faso',
 'Burundi',
 'Cameroon',
 'Central African Republic',
 'Chad',
 'Comoros',
 'Congo, Democratic Republic of',
 'Congo, Republic of',
 'Eritrea',
 'Ethiopia',
 'Guinea-Bissau',
 'Haiti',
 'Iraq',
 'Kiribati',
 'Lebanon',
 'Libya',
 'Mali',
 'Marshall Islands',
 'Micronesia, Federated States of',
 'Mozambique',
 'Myanmar',
 'Niger',
 'Nigeria',
 'Papua New Guinea',
 'Solomon Islands',
 'South Sudan',
 'Sudan',
 'Syrian Arab Republic',
 'São Tomé and Príncipe',
 'Timor-Leste',
 'Tuvalu',
 'Ukraine',
 'Venezuela, RB',
 'West Bank and Gaza (territory)',
 'Yemen, Republic of',
 'Zimbabwe']

Step 8 Preparing (Cleaning) "Health Expenditure" and "GDP" Files

In [ ]:
gdphexp_raw["Series Name"].drop_duplicates().tolist()

['Current health expenditure per capita (current US$)',
 'Current health expenditure per capita, PPP (current international $)',
 'Domestic general government health expenditure (% of current health expenditure)',
 'Domestic general government health expenditure (% of general government expenditure)',
 'Domestic general government health expenditure per capita, PPP (current international $)',
 'Domestic private health expenditure per capita (current US$)',
 'Domestic general government health expenditure (% of GDP)',
 'Domestic general government health expenditure per capita (current US$)',
 'Domestic private health expenditure (% of current health expenditure)',
 'Domestic private health expenditure per capita, PPP (current international $)',
 'External health expenditure (% of current health expenditure)',
 'External health expenditure per capita, PPP (current international $)',
 'GDP per capita (constant 2015 US$)',
 'GDP per capita (current LCU)',
 'GDP per capita growth (annual %)',
 'GDP per capita, PPP (current international $)',
 'GDP per capita, PPP (constant 2021 international $)',
 'GDP per capita (current US$)',
 'GDP per capita (constant LCU)',
 nan]

In [ ]:
gdp_part = gdphexp_raw[gdphexp_raw["Series Name"] == "GDP per capita (current US$)"].copy()

hexp_part = gdphexp_raw[gdphexp_raw["Series Name"] == "Current health expenditure per capita (current US$)"].copy()

Step 9 Reshaping GDP from wide format to long format

In [ ]:
gdp_part["Country Name"] = gdp_part["Country Name"].apply(clean_country)
gdp_part = gdp_part[gdp_part["Country Name"].isin(countries)].copy()

year_cols = [c for c in gdp_part.columns if "[YR" in str(c)]

gdp = gdp_part.melt(
    id_vars=["Country Name"],
    value_vars=year_cols,
    var_name="year",
    value_name="gdp_per_capita_current_usd"
)

gdp = gdp.rename(columns={"Country Name": "country"})

gdp["year"] = gdp["year"].str.extract(r"(\d{4})")
gdp["year"] = pd.to_numeric(gdp["year"], errors="coerce")

gdp["gdp_per_capita_current_usd"] = pd.to_numeric(
    gdp["gdp_per_capita_current_usd"].replace("..", pd.NA),
    errors="coerce"
)

gdp = gdp[["country", "year", "gdp_per_capita_current_usd"]].copy()

gdp.head()

                         country  year  gdp_per_capita_current_usd
0                    Afghanistan  2000                  174.930991
1                   Burkina Faso  2000                  248.908527
2                       Cameroon  2000                  708.565732
3       Central African Republic  2000                  239.154134
4  Congo, Democratic Republic of  2000                  377.925421

In [ ]:
len(gdp["country"].unique())

37

In [ ]:
sorted(gdp["country"].unique())

['Afghanistan',
 'Burkina Faso',
 'Burundi',
 'Cameroon',
 'Central African Republic',
 'Chad',
 'Comoros',
 'Congo, Democratic Republic of',
 'Congo, Republic of',
 'Eritrea',
 'Ethiopia',
 'Guinea-Bissau',
 'Haiti',
 'Iraq',
 'Kiribati',
 'Lebanon',
 'Libya',
 'Mali',
 'Marshall Islands',
 'Micronesia, Federated States of',
 'Mozambique',
 'Myanmar',
 'Niger',
 'Nigeria',
 'Papua New Guinea',
 'Solomon Islands',
 'South Sudan',
 'Sudan',
 'Syrian Arab Republic',
 'São Tomé and Príncipe',
 'Timor-Leste',
 'Tuvalu',
 'Ukraine',
 'Venezuela, RB',
 'West Bank and Gaza (territory)',
 'Yemen, Republic of',
 'Zimbabwe']

Step 10 Reshaping Health expenditure from wide format to long format

In [ ]:
hexp_part["Country Name"] = hexp_part["Country Name"].apply(clean_country)
hexp_part = hexp_part[hexp_part["Country Name"].isin(countries)].copy()

year_cols = [c for c in hexp_part.columns if "[YR" in str(c)]

hexp = hexp_part.melt(
    id_vars=["Country Name"],
    value_vars=year_cols,
    var_name="year",
    value_name="health_expenditure_per_capita_current_usd"
)

hexp = hexp.rename(columns={"Country Name": "country"})

hexp["year"] = hexp["year"].str.extract(r"(\d{4})")
hexp["year"] = pd.to_numeric(hexp["year"], errors="coerce")

hexp["health_expenditure_per_capita_current_usd"] = pd.to_numeric(
    hexp["health_expenditure_per_capita_current_usd"].replace("..", pd.NA),
    errors="coerce"
)

hexp = hexp[["country", "year", "health_expenditure_per_capita_current_usd"]].copy()

hexp.head()

,country,year,health_expenditure_per_capita_current_usd
0,Afghanistan,2000,NaN
1,Burkina Faso,2000,10.009027
2,Cameroon,2000,30.438097
3,Central African Republic,2000,9.912335
4,"Congo, Democratic Republic of",2000,17.520720

In [ ]:
len(hexp["country"].unique())

37

In [ ]:
sorted(hexp["country"].unique())

['Afghanistan',
 'Burkina Faso',
 'Burundi',
 'Cameroon',
 'Central African Republic',
 'Chad',
 'Comoros',
 'Congo, Democratic Republic of',
 'Congo, Republic of',
 'Eritrea',
 'Ethiopia',
 'Guinea-Bissau',
 'Haiti',
 'Iraq',
 'Kiribati',
 'Lebanon',
 'Libya',
 'Mali',
 'Marshall Islands',
 'Micronesia, Federated States of',
 'Mozambique',
 'Myanmar',
 'Niger',
 'Nigeria',
 'Papua New Guinea',
 'Solomon Islands',
 'South Sudan',
 'Sudan',
 'Syrian Arab Republic',
 'São Tomé and Príncipe',
 'Timor-Leste',
 'Tuvalu',
 'Ukraine',
 'Venezuela, RB',
 'West Bank and Gaza (territory)',
 'Yemen, Republic of',
 'Zimbabwe']

Step 11 Creating Main Chart

In [ ]:
years = list(range(2000, 2025))

panel = pd.DataFrame(
    list(itertools.product(countries, years)),
    columns=["country", "year"]
)

Step 12 Merging All

In [ ]:
final = panel.merge(md, on=["country", "year"], how="left")
final = final.merge(nurse, on=["country", "year"], how="left")
final = final.merge(life, on=["country", "year"], how="left")
final = final.merge(gdp, on=["country", "year"], how="left")
final = final.merge(hexp, on=["country", "year"], how="left")
final = final.merge(gni, on=["country", "year"], how="left")

final.head()

,country,year,physicians_per_1000,nurses_midwives_per_1000,life_expectancy,gdp_per_capita_current_usd,health_expenditure_per_capita_current_usd,gni_ppp_current_international
0,Afghanistan,2000,NaN,NaN,55.005,174.930991,NaN,790.0
1,Afghanistan,2001,NaN,NaN,55.511,138.706822,NaN,750.0
2,Afghanistan,2002,NaN,NaN,56.225,178.954088,16.706974,940.0
3,Afghanistan,2003,NaN,NaN,57.171,198.871116,17.746025,980.0
4,Afghanistan,2004,NaN,NaN,57.810,221.763654,21.423004,980.0

Step 13 Final Checks

13-1 Check for duplicates

In [ ]:
final.duplicated(subset=["country", "year"]).sum()

np.int64(0)

13-2 Check Final shape

In [ ]:
final.shape

(950, 8)

13-3 Check Missings

In [ ]:
final.isna().sum()

country                                        0
year                                           0
physicians_per_1000                          906
nurses_midwives_per_1000                     566
life_expectancy                              173
gdp_per_capita_current_usd                    66
health_expenditure_per_capita_current_usd    117
gni_ppp_current_international                112
dtype: int64

13-4 Checking some rows of the final file

In [ ]:
final.sample(10)

,country,year,physicians_per_1000,nurses_midwives_per_1000,life_expectancy,gdp_per_capita_current_usd,health_expenditure_per_capita_current_usd,gni_ppp_current_international
452,Marshall Islands,2002,NaN,NaN,63.848,2566.067088,309.727417,3540.0
555,Niger,2005,NaN,NaN,53.320,318.643122,18.671402,940.0
413,Libya,2013,NaN,6.978,72.339,11951.713413,594.653381,21030.0
614,Papua New Guinea,2014,NaN,NaN,64.198,2723.175298,89.080612,3440.0
530,Myanmar,2005,NaN,0.770,61.720,252.685193,7.652545,1860.0
441,Mali,2016,NaN,0.387,58.286,872.468587,27.580862,2480.0
423,Libya,2023,NaN,NaN,NaN,6026.515187,470.403473,14530.0
942,Zimbabwe,2017,NaN,2.496,60.263,3445.449410,91.871994,10480.0
663,Solomon Islands,2013,NaN,1.915,69.007,2161.386275,98.999657,2400.0
294,Guinea-Bissau,2019,NaN,NaN,62.161,811.216426,53.983910,2280.0

Step 14 Saving final File

In [ ]:
final = final.sort_values(["country","year"]).reset_index(drop=True)

In [ ]:
final.to_csv("fcas_final_dataset.csv", index=False)
final.to_excel("fcas_final_dataset.xlsx", index=False)

Step 15 Downloading Final Dataset

In [ ]:
files.download("fcas_final_dataset.xlsx")

In [ ]:
files.download("fcas_final_dataset.csv")